apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza
  template:
    metadata:
      labels:
        app: pizza
    spec:
      containers:
        - name: pizza
          image: mreider/pizza:28
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis