apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: pizza-shop
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        args:
          - "--config=/etc/otel-collector-config.yaml"
        ports:
        - containerPort: 4317
        - containerPort: 4318
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config
        env:
        - name: DT_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dynatrace-secrets
              key: DT_ENDPOINT
        - name: DT_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: dynatrace-secrets
              key: DT_API_TOKEN
      volumes:
      - name: config-volume
        configMap:
          name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: pizza-shop
spec:
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317
  - name: http
    port: 4318
    targetPort: 4318
  selector:
    app: otel-collector
